Adding simple MessagesManager
ServerOpenMC/PluginV2 pull request #19
Opened 2024-11-24 21:43 UTC by AxenoDev

## Pour que votre Pull Request soit accepté, il vous faut :
* Votre code suit-il le [Code de Conduite](https://github.com/ServerOpenMC/PluginV2/blob/master/CODE_OF_CONDUCT.md) ? :
* Votre code se compile-il en local ? :
* Avez-vous supprimez au maximum les imports non utilisé? :
* Fournissez un Profileur (/spark profiler) lorsque vous éxécuter vos commandes, méthodes :

## Decrivez vos changements
*Clairement et avec des screenshots si nécessaires*
J'ai simplifié l'utilisation de MessageManager.

Maintenant il faut juste faire un `MessagesManager msg = new MessagesManager(Prefix.YOURPREFIX)`

```java
MessagesManager msg = new MessagesManager(Prefix.OPENMC);

@Command("hello")
public void hello(CommandSender sender) {
    msg.info(sender, "Hello, world!");
    msg.error(sender, "Hello, world!");
    msg.warning(sender, "Hello, world!");
    msg.success(sender, "Hello, world!");
}
```

J'ai mis le sendMessageType en deprecated

*J'ai pas réussi à revert les commit de home*

2024-11-24 21:53 UTC, Xernas78 approved these changes
Ok, ça va être pratique ça (en + vous faites des petites PR)

2024-11-25 06:31 UTC, MathiasDPX commented
Rempli le template axeno

2024-11-25 06:33 UTC, MathiasDPX requested changes

2024-11-25 06:33 UTC, MathiasDPX commented on src/main/java/fr/openmc/core/utils/messages/MessagesManager.java
> +     *
C'est @deprecated et change ceux qui l'utilise ducoup

2024-11-25 17:18 UTC, AxenoDev commented
> Rempli le template axeno

De quoi rempli le template ?

2024-11-25 19:15 UTC, MathiasDPX commented on src/main/java/fr/openmc/core/utils/messages/MessagesManager.java
> +     *
c'est dans la javadocs qu'il faut le mettre

2024-11-25 20:46 UTC, Xernas78 commented on src/main/java/fr/openmc/core/utils/messages/MessagesManager.java
> +     *
Son commit a corrigé

2024-11-26 19:39 UTC, MathiasDPX approved these changes

2024-11-26 19:39 UTC, merged