Adding spawn system
ServerOpenMC/PluginV2 pull request #2
Opened 2024-10-31 22:45 UTC by AxenoDev

J'ai ajouter un sysème de spawn.

```cmd
/spawn [player]
/setspawn
```

le spawn est save dans /data/spawn.yml

2024-10-31 23:03 UTC, MathiasDPX requested changes

2024-10-31 23:03 UTC, MathiasDPX commented on src/main/java/fr/openmc/core/OMCPlugin.java
> +    @Getter private SpawnManager spawnManager;
Fais plutot SpawnManager.getInstance, ça évite de surcharger la classe principale

2024-10-31 23:03 UTC, MathiasDPX commented on src/main/java/fr/openmc/core/commands/utils/Spawn.java
> +    public void spawn(Player player, @Default("me") Player target) {
Tu peux changer player en CommandSender pour que la console puisse bouger qqn

2024-10-31 23:03 UTC, MathiasDPX commented on src/main/java/fr/openmc/core/features/utils/spawn/SpawnManager.java
> +            plugin.saveResource("data/spawn.yml", false);
Pourquoi un fichier à part ?

2024-10-31 23:04 UTC, MathiasDPX commented
Et rajoute des tests unitaires

`We <3 JUnit`

2024-10-31 23:05 UTC, MathiasDPX requested changes

2024-10-31 23:05 UTC, MathiasDPX commented on src/main/java/fr/openmc/core/commands/utils/SetSpawn.java
> +    @CommandPermission("omc.command.setspawn")
1. omc.commands.* est donné par défaut
2. command**s** pas command

2024-10-31 23:05 UTC, MathiasDPX commented on src/main/java/fr/openmc/core/commands/utils/Spawn.java
> +    @Description("Permet de se rendre au spawn")
Rajoute une perm

2024-10-31 23:08 UTC, AxenoDev commented on src/main/java/fr/openmc/core/features/utils/spawn/SpawnManager.java
> +            plugin.saveResource("data/spawn.yml", false);
Je ne voulais pas sur charger le config.yml
dcp j'ai fait un fichier data ou il y a les yml qui ne faut pas modifier

2024-10-31 23:21 UTC, MathiasDPX commented on src/main/java/fr/openmc/core/features/utils/spawn/SpawnManager.java
> +            plugin.saveResource("data/spawn.yml", false);
C'est un vrai probleme:
Gros fichier config
Petit fichier**s** config

2024-10-31 23:28 UTC, AxenoDev commented on src/main/java/fr/openmc/core/features/utils/spawn/SpawnManager.java
> +            plugin.saveResource("data/spawn.yml", false);
pour moi petit fichiers config
c'est pour ça que j'ai fait a part

2024-11-01 00:40 UTC, MathiasDPX commented on src/main/java/fr/openmc/core/features/utils/spawn/SpawnManager.java
> +            plugin.saveResource("data/spawn.yml", false);
1 contre 6,
La commu a tranché

2024-11-01 00:48 UTC, MathiasDPX approved these changes

2024-11-01 01:02 UTC, MathiasDPX approved these changes

2024-11-01 07:58 UTC, iambibi approved these changes

2024-11-01 14:02 UTC, merged