[V1 PORTAGE] Contest and Mailboxes
ServerOpenMC/PluginV2 pull request #37
Opened 2024-12-22 09:05 UTC by iambibi

## Pour que votre Pull Request soit accepté, il vous faut :
* Votre code suit-il le [Code de Conduite](https://github.com/ServerOpenMC/PluginV2/blob/master/CODE_OF_CONDUCT.md) ? : oui
* Votre code se compile-il en local ? : oui
* Avez-vous supprimez au maximum les imports non utilisé? : oui
* Fournissez un Profileur (/spark profiler) lorsque vous éxécuter vos commandes, méthodes : en attente que la pr soit plus une draft 

## Decrivez vos changements
*Clairement et avec des screenshots si nécessaires*
J'ai ajouté les Contests avec des optimisations en plus, toutes les données sont en local et sont sauvegardés lors du shutdown.
Je vais ajouté la Mailbox

2024-12-22 09:07 UTC, iambibi commented
Att je vois pas pourquoi il m'a remis les commits qui sont passé hier

2024-12-22 14:06 UTC, ltuffery reviewed
Il manque beaucoup d'appels à `this` pour que nous puissions comprendre que tu fais référence à l'instance présente, et attention à la forêt de `if`. Fais attention aussi, tu ne respectes pas le `CODE_OF_CONDUCT`. Je n'ai pas encore tout regardé, mais j'ai déjà relevé ça. Maintenant, c'est à prendre ou à laisser

2024-12-22 14:06 UTC, ltuffery commented on src/main/java/fr/openmc/core/features/contest/managers/ContestPlayerManager.java
> +        return "";
Ceci est plus optimisé, mais pas plus clair
```suggestion
        int[] seuils = {10000, 2500, 2000, 1500, 1000, 750, 500, 250, 100, 0};
        String[] categories = {
            "Dictateur en ",
            "Colonel en ",
            "Addict en ",
            "Dieu en ",
            "Légende en ",
            "Sénior en ",
            "Pro en ",
            "Semi-Pro en ",
            "Amateur en ",
            "Noob en "
        };
        
        for (int i = 0; i < seuils.length; i++) {
            if (points >= seuils[i]) {
                return categories[i];
            }
        }

        return "";
```

2024-12-22 14:06 UTC, ltuffery commented on src/main/java/fr/openmc/core/features/contest/managers/ContestPlayerManager.java
> +        return "";
Tu as exactement le même code plus haut, peut-être le mettre en une seule méthode.

2024-12-22 14:21 UTC, iambibi commented
> Il manque beaucoup d'appels à `this` pour que nous puissions comprendre que tu fais référence à l'instance présente, et attention à la forêt de `if`. Fais attention aussi, tu ne respectes pas le `CODE_OF_CONDUCT`. Je n'ai pas encore tout regardé, mais j'ai déjà relevé ça. Maintenant, c'est à prendre ou à laisser

Tout d'abord, merci de ta review je vais prendre tes conseils bien évidemment.

2024-12-22 14:23 UTC, iambibi commented on src/main/java/fr/openmc/core/features/contest/ContestData.java
> +    }
Oui elle m'est utilisé car dans la db j'ai l'entier du camp stocké : exemple
`int campInteger = contestManager.dataPlayer.get(player.getUniqueId().toString()).getCamp();
 return contestManager.data.get("camp" + campInteger);`

2024-12-22 14:23 UTC, iambibi commented on src/main/java/fr/openmc/core/features/contest/ContestPlayer.java
> +    }
Bonne remarque

2024-12-22 14:26 UTC, ltuffery commented on src/main/java/fr/openmc/core/features/contest/ContestData.java
> +    }
D'accord, je te laisse clore cette conversation car je ne peux pas le faire. Peut-être un manque de permissions.

2024-12-22 14:29 UTC, iambibi commented on src/main/java/fr/openmc/core/features/contest/managers/ContestPlayerManager.java
> +        return "";
Je comptais faire une refonte de ceci, je me disais que ça fait moche et un peu bete de faire que des if

2024-12-22 14:35 UTC, ltuffery commented on src/main/java/fr/openmc/core/features/contest/commands/ContestCommand.java
> +    public void settrade(Player player) {
```suggestion
    public void setTrade(Player player) {
```

2024-12-22 14:35 UTC, iambibi commented on src/main/java/fr/openmc/core/features/contest/managers/ContestPlayerManager.java
> +        return "";
Oui effectivement

2024-12-22 14:38 UTC, iambibi commented on src/main/java/fr/openmc/core/features/contest/commands/ContestCommand.java
> +    public void settrade(Player player) {
Ceci est une commande teste je vais la supprimer j'ai missclick lors du commit

2024-12-22 14:39 UTC, ltuffery commented on src/main/java/fr/openmc/core/features/contest/ContestPlayer.java
> +@Getter
Tu ne compiles plus à cause du `@Getter`, on ne peut pas le mettre sur des `record`.
```suggestion
```

2024-12-22 14:40 UTC, iambibi commented on src/main/java/fr/openmc/core/features/contest/ContestPlayer.java
> +@Getter
Attendez je n'avais pas encore build ^^

2024-12-22 14:40 UTC, ltuffery commented on src/main/java/fr/openmc/core/features/contest/commands/ContestCommand.java
> +    public void settrade(Player player) {
Ah pardon, je n'avais pas vu.

2024-12-22 14:41 UTC, iambibi commented on src/main/java/fr/openmc/core/features/contest/commands/ContestCommand.java
> +    public void settrade(Player player) {
Ce n'est pas grave, votre aide est importante. Comptez vous développez sur le plugin ou juste améliorer le code dans le pr?

2024-12-22 14:43 UTC, ltuffery commented on src/main/java/fr/openmc/core/features/contest/commands/ContestCommand.java
> +    public void settrade(Player player) {
Pour l'instant, je ne compte faire que des reviews sur les différentes PR pour comprendre la construction du code, etc. Plus tard, il est fort probable que je contribue. Je me tâte déjà à faire une première PR pour ajouter des tests unitaires qui manquent cruellement

2024-12-22 14:47 UTC, iambibi commented on src/main/java/fr/openmc/core/features/contest/commands/ContestCommand.java
> +    public void settrade(Player player) {
ahh... oui les tests unitaires. Gyro est dans la même optique que vous. Il veut ses tests unitaires mais franchement je n'arrive pas à faire des tests unitaires. Je ne sais pas quoi tester. Je pense que regarder une vidéo sur les tests unitaires seraient une bonne idée de ma part

2024-12-22 15:22 UTC, ltuffery commented on src/main/java/fr/openmc/core/features/contest/commands/ContestCommand.java
> +    public void settrade(Player player, @Named("trade") String trade, int amount, int amount_shell) {
A close, modif faite sur le commit [51d6e94](https://github.com/ServerOpenMC/PluginV2/pull/37/commits/51d6e94b41da5dd4a73124c8996084d62c11edf5)

2024-12-23 13:54 UTC, ltuffery commented on src/main/java/fr/openmc/core/features/contest/ContestData.java
> +    }
Utilise Lombok

2024-12-23 13:54 UTC, ltuffery commented on src/main/java/fr/openmc/core/utils/PapiAPI.java
> +        }
```suggestion
        hasPAPI = Bukkit.getPluginManager().getPlugin("PlaceholderAPI") != nulll;
```

2024-12-23 14:16 UTC, iambibi commented
(J'attends que j'aies fini ce que je fais pour commit ces fichiers qui font crash le build)

2024-12-23 15:33 UTC, ltuffery requested changes

2024-12-23 15:33 UTC, ltuffery commented on src/main/java/fr/openmc/core/features/contest/menu/ContributionMenu.java
> +        Material shell_contest = CustomItemRegistry.getByName("omc_contest:contest_shell").getBest().getType();
Ce nom de variable ne respecte pas les règles de contribution.
https://github.com/ServerOpenMC/PluginV2/blob/master/CONTRIBUTING.md#-style-de-code
```suggestion
        Material shellContest = CustomItemRegistry.getByName("omc_contest:contest_shell").getBest().getType();
```

2024-12-23 15:33 UTC, ltuffery commented on src/main/java/fr/openmc/core/features/contest/menu/TradeMenu.java
> +        Material shell_contest = CustomItemRegistry.getByName(namespaceShellContest).getBest().getType();
Ce nom de variable ne respecte pas les règles de contribution.
https://github.com/ServerOpenMC/PluginV2/blob/master/CONTRIBUTING.md#-style-de-code
```suggestion
        Material shellContest = CustomItemRegistry.getByName(namespaceShellContest).getBest().getType();
```

2024-12-23 15:33 UTC, ltuffery commented on src/main/java/fr/openmc/core/features/contest/menu/TradeMenu.java
> +                ItemStack shell_contestItem = CustomStack.getInstance(namespaceShellContest).getItemStack();
Ce nom de variable ne respecte pas les règles de contribution.
https://github.com/ServerOpenMC/PluginV2/blob/master/CONTRIBUTING.md#-style-de-code
```suggestion
                ItemStack shellContestItem = CustomStack.getInstance(namespaceShellContest).getItemStack();
```

2024-12-23 15:33 UTC, ltuffery commented on src/main/java/fr/openmc/core/features/contest/menu/TradeMenu.java
> +                                ItemStack newshell_contestItem = CustomStack.getInstance(namespaceShellContest).getItemStack();
Ce nom de variable ne respecte pas les règles de contribution.
https://github.com/ServerOpenMC/PluginV2/blob/master/CONTRIBUTING.md#-style-de-code
```suggestion
                                ItemStack newShellContestItem = CustomStack.getInstance(namespaceShellContest).getItemStack();
```

2024-12-23 15:35 UTC, iambibi commented on src/main/java/fr/openmc/core/features/contest/menu/TradeMenu.java
> +                                ItemStack newshell_contestItem = CustomStack.getInstance(namespaceShellContest).getItemStack();
Oula mais oui je l'avais fais quand je débutais et ouais j'ai fais n'importe quoi

2024-12-23 15:36 UTC, ltuffery commented
Le portage des fonctionnalités actuelles devient long et compliqué. Cela pourrait être bien de faire les Mailboxes dans une autre PR ?

2024-12-23 15:37 UTC, ltuffery commented on src/main/java/fr/openmc/core/features/contest/menu/TradeMenu.java
> +                                ItemStack newshell_contestItem = CustomStack.getInstance(namespaceShellContest).getItemStack();
Pas de problème, les revues sont là pour avoir un deuxième regard sur le code et rattraper nos oublis

2024-12-23 15:40 UTC, iambibi commented
> Le portage des fonctionnalités actuelles devient long et compliqué. Cela pourrait être bien de faire les Mailboxes dans une autre PR ?

Non non, le problème c'est que j'ai besoin des Mailboxes et la je suis parti sur la config de ItemAdder. Je m'éparpille dans trop de choses. Je l'ai mis en draft c'était pour bien signifier que ça n'allait pas être fini dans 1h

2024-12-23 15:43 UTC, ltuffery commented
> > Le portage des fonctionnalités actuelles devient long et compliqué. Cela pourrait être bien de faire les Mailboxes dans une autre PR ?
> 
> Non non, le problème c'est que j'ai besoin des Mailboxes et la je suis parti sur la config de ItemAdder. Je m'éparpille dans trop de choses. Je l'ai mis en draft c'était pour bien signifier que ça n'allait pas être fini dans 1h

Ce n'est pas le problème, mais la PR contient 46 fichiers, pas encore tous révisés, et nous allons nous retrouver avec une fonctionnalité en plus. Ça commence à faire beaucoup. Mais sinon, oui, tout ne se fait pas en 1h 😂. Bref, si il faut absolument la MailBox ici, alors faisons comme ça

2024-12-23 15:45 UTC, iambibi commented
> > > Le portage des fonctionnalités actuelles devient long et compliqué. Cela pourrait être bien de faire les Mailboxes dans une autre PR ?
> > 
> > 
> > Non non, le problème c'est que j'ai besoin des Mailboxes et la je suis parti sur la config de ItemAdder. Je m'éparpille dans trop de choses. Je l'ai mis en draft c'était pour bien signifier que ça n'allait pas être fini dans 1h
> 
> Ce n'est pas le problème, mais la PR contient 46 fichiers, pas encore tous révisés, et nous allons nous retrouver avec une fonctionnalité en plus. Ça commence à faire beaucoup. Mais sinon, oui, tout ne se fait pas en 1h 😂. Bref, si il faut absolument la MailBox ici, alors faisons comme ça

Oui... c'est vrai que ça fait beaucoup de fichier. Après tout le plugin ne va pas en prod donc je pense que c'est faisable.

2024-12-23 16:12 UTC, iambibi commented
Je corrige les bugs que j'ai ^^

2024-12-23 16:58 UTC, iambibi commented
Voici le profileur, j'ai fais un peu près toutes les actions possibles : https://spark.lucko.me/hIAsv2Kaqi

2024-12-23 17:17 UTC, ltuffery reviewed
Voici les derniers points que j'ai pu relever. Il y a des morceaux de code qui devront peut-être être modifiés plus tard. Mais sinon, c'est tout. Oui, désolé de chipoter sur 2 commentaires, mais je trouve que ce sont des parties importantes

2024-12-23 17:17 UTC, ltuffery commented on src/main/java/fr/openmc/core/features/contest/listeners/ContestListener.java
> +                } //attention ne pas modifier les valeurs de départ des contest sinon le systeme va broke
On ne sait pas trop vers qui pointe ce commentaire. Mets-le à la ligne si c'est pour expliquer la condition ci-dessous, sinon mets-le au-dessus de la ligne correspondante et précise un peu plus, car je ne comprends pas de quelle valeur de départ on parle et quel système va casser

2024-12-23 17:17 UTC, ltuffery commented on src/main/java/fr/openmc/core/features/contest/listeners/ContestListener.java
> +        // tout les minutes
```suggestion
        // 1200 s = 1 min
```

2024-12-23 17:17 UTC, ltuffery commented on src/main/java/fr/openmc/core/features/contest/managers/ContestManager.java
> +//        eventRunnable.runTaskTimer(plugin, 0, 100);
À supprimer ?

2024-12-23 17:38 UTC, iambibi commented on src/main/java/fr/openmc/core/features/contest/managers/ContestManager.java
> +//        eventRunnable.runTaskTimer(plugin, 0, 100);
Je préfère le garder pour me debug le programme si j'en ai besoin

2024-12-23 18:34 UTC, ltuffery approved these changes

2024-12-23 18:36 UTC, ltuffery commented
> mmh je crois qu'un maintener doit passer par la

Oui, mais je trouve important de dire que, de mon côté, je n'ai plus grand-chose à dire question review 😂

2024-12-23 18:37 UTC, iambibi commented
> > mmh je crois qu'un maintener doit passer par la
> 
> Oui, mais je trouve important de dire que, de mon côté, je n'ai plus grand-chose à dire question review 😂

Bien évidemment !

2024-12-24 09:44 UTC, MathiasDPX approved these changes

2024-12-24 09:44 UTC, merged